/// Static reference data for the sign-up location fields.
class AppLocations {
  AppLocations._();

  /// Country options for the sign-up Country dropdown. Maps directly to the
  /// backend `country` field. City is entered as free text alongside it.
  static const List<String> countries = [
    'Algeria',
    'Argentina',
    'Australia',
    'Austria',
    'Bahrain',
    'Belgium',
    'Brazil',
    'Canada',
    'China',
    'Denmark',
    'Egypt',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'India',
    'Indonesia',
    'Ireland',
    'Italy',
    'Japan',
    'Jordan',
    'Kuwait',
    'Lebanon',
    'Malaysia',
    'Mexico',
    'Morocco',
    'Netherlands',
    'New Zealand',
    'Nigeria',
    'Norway',
    'Oman',
    'Pakistan',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Saudi Arabia',
    'Singapore',
    'South Africa',
    'South Korea',
    'Spain',
    'Sweden',
    'Switzerland',
    'Tunisia',
    'Turkey',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Other',
  ];
}
