# -*- coding: utf-8 -*-
"""Proposition de banque « Temps Réflexif » — 20 situations, format SJT.

Construite sur le modèle du Situational Judgment Test (Motowidlo, Dunnette &
Carter, 1990) et sur le modèle processuel de régulation émotionnelle de Gross
(1998). Rédigée POUR ÊTRE VALIDÉE par le psychologue : les cotations proposées
sont une clé de départ, destinée à être confrontée à une cotation de panel.

Trois défauts de la banque actuelle corrigés par construction :

1. POSITION NEUTRE. Dans la banque livrée, « A » est la réponse impulsive des
   soixante fiches et « B » toujours « respirer » : la grille s'apprend en deux
   situations. Ici l'ordre est mélangé à la rédaction, item par item.

2. MEILLEURE RÉPONSE DISTRIBUÉE. Cinq items par type gagnant (respirer,
   attendre, demander, reformuler) : cocher toujours le même libellé ne paie
   jamais plus d'un quart des items.

3. SUPPORT ÉCRIT RÉELLEMENT ÉCRIT. La banque livrée déclare 60 mini-vidéos et
   aucun message ; elle ne fournit d'ailleurs aucun texte littéral. Six items
   ici sont des messages, avec leur contenu exact — jouables sans vidéo.
"""

IMPULSIVE = "RESPOND_IMPULSIVELY"
BREATHE = "BREATHE_ANALYZE"
WAIT = "WAIT"
ASK = "ASK_FOR_MORE_INFORMATION"
REFORMULATE = "REFORMULATE_CALMLY"

# (type, texte, score, justification)
SITUATIONS = [
    dict(id="TR-101", cat=1, cat_label="Message provocateur ou remarque déplacée", targetEmotion="ANGER",
         diff="LOW", medium="WRITTEN", title="Le message qui corrige en public",
         context="Dans le canal d'équipe, un collègue reprend publiquement une phrase que vous venez d'écrire, sur un ton appuyé.",
         message="« Ce n'est pas du tout ça. Tu devrais relire la procédure avant de poster. »",
         question="Que faites-vous maintenant ?",
         choices=[
             (WAIT, "Ne rien poster pour l'instant.", 1, "Évite l'escalade, mais laisse la remarque seule à l'écran."),
             (REFORMULATE, "Répondre dans le canal, calmement, avec la référence exacte.", 3, "Rétablit le fait là où l'erreur a été affirmée, sans attaquer."),
             (IMPULSIVE, "Répondre sur le même ton, tout de suite.", 0, "Transforme un désaccord mineur en affrontement public."),
             (ASK, "Lui écrire en privé pour comprendre ce qu'il vise.", 2, "Clarifie l'intention, mais laisse le canal sans réponse."),
             (BREATHE, "Prendre un instant avant de réagir.", 1, "Coupe l'impulsion, ne règle rien à soi seul."),
         ]),
    dict(id="TR-102", cat=1, cat_label="Message provocateur ou remarque déplacée", targetEmotion="ANGER",
         diff="HIGH", medium="VIDEO", title="La plaisanterie devant le client",
         context="En réunion avec un client, un collègue glisse une plaisanterie sur votre manière de parler. Deux personnes rient.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (BREATHE, "Marquer un temps avant de reprendre la parole.", 3, "Devant un client, la maîtrise visible vaut mieux que la mise au point : elle protège la relation et votre position."),
             (IMPULSIVE, "Répliquer immédiatement sur le même registre.", 0, "Déplace le sujet vers un conflit interne, devant le client."),
             (REFORMULATE, "Reprendre le fil en nommant la remarque devant tous.", 1, "Légitime, mais installe la tension dans la réunion client."),
             (WAIT, "Laisser passer et poursuivre la réunion.", 2, "Préserve la réunion ; demande un retour au collègue ensuite."),
             (ASK, "Demander devant le groupe ce qu'il veut dire.", 1, "Force une explication publique, au mauvais moment."),
         ]),
    dict(id="TR-103", cat=2, cat_label="Critique soudaine ou accusation injuste", targetEmotion="ANGER",
         diff="MODERATE", medium="VIDEO", title="Le reproche sur un dossier partagé",
         context="En réunion, une collègue affirme que le retard du dossier vient de vous. Vous savez que la validation attendait ailleurs.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (ASK, "Demander sur quelle étape précise elle se fonde.", 3, "Ouvre le fait sans nier ni accuser : le malentendu se dissout de lui-même."),
             (IMPULSIVE, "Corriger immédiatement, fermement.", 1, "Légitime mais confrontationnel : risque d'escalade publique."),
             (WAIT, "Ne rien dire pour l'instant.", 0, "Laisse une affirmation fausse s'installer devant l'équipe."),
             (BREATHE, "Respirer avant de répondre.", 2, "Bonne première étape, insuffisante seule."),
             (REFORMULATE, "Reprendre calmement la chronologie réelle.", 1, "Juste, mais affirme votre version avant d'avoir vérifié la sienne."),
         ]),
    dict(id="TR-104", cat=2, cat_label="Critique soudaine ou accusation injuste", targetEmotion="FEAR",
         diff="HIGH", medium="WRITTEN", title="Le courriel en copie à la direction",
         context="Vous recevez un courriel mettant en cause votre travail, avec la direction en copie.",
         message="« Le livrable ne correspond pas à ce qui avait été convenu. Je mets Mme Riahi en copie pour arbitrage. »",
         question="Que faites-vous maintenant ?",
         choices=[
             (ASK, "Répondre en demandant quel point précis diverge.", 3, "Un désaccord porté devant l'arbitre se règle en établissant les faits, pas en plaidant."),
             (REFORMULATE, "Répondre à tous en rappelant le cadrage validé.", 2, "Défendable, mais engage un échange contradictoire sous les yeux de la direction."),
             (BREATHE, "Prendre un moment avant de répondre.", 1, "Nécessaire vu la mise en copie ; ne suffit pas."),
             (WAIT, "Attendre la réaction de la direction.", 1, "Laisse d'autres cadrer le sujet à votre place."),
             (IMPULSIVE, "Répondre à tous immédiatement pour vous défendre.", 0, "Fige un conflit écrit devant la hiérarchie."),
         ]),
    dict(id="TR-105", cat=3, cat_label="Imprévu nécessitant une décision rapide", targetEmotion="FEAR",
         diff="MODERATE", medium="VIDEO", title="L'absence de dernière minute",
         context="Trente minutes avant un atelier que vous animez à deux, votre binôme prévient qu'il ne pourra pas venir.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (BREATHE, "Prendre un instant pour reprendre le plan de l'atelier.", 3, "L'échéance est proche mais tenable : trente secondes de cadrage valent mieux qu'une improvisation."),
             (ASK, "Lui demander ce qu'il avait prévu pour sa partie.", 1, "Utile, mais dépend de sa disponibilité immédiate."),
             (IMPULSIVE, "Commencer l'atelier sans rien changer.", 1, "Tient l'horaire, au prix d'une seconde moitié non préparée."),
             (WAIT, "Reporter l'atelier.", 0, "Coût disproportionné : les participants sont déjà là."),
             (REFORMULATE, "Annoncer aux participants un format réduit.", 2, "Honnête et praticable, mais décidé avant d'avoir regardé le contenu."),
         ]),
    dict(id="TR-106", cat=3, cat_label="Imprévu nécessitant une décision rapide", targetEmotion="FEAR",
         diff="HIGH", medium="VIDEO", title="La panne avant la démonstration",
         context="Cinq minutes avant une démonstration client, l'outil affiche une erreur que vous n'aviez jamais vue.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (ASK, "Appeler le support technique pour identifier l'erreur.", 3, "Sur un incident inconnu à échéance immédiate, l'information manquante est le seul verrou."),
             (BREATHE, "Respirer et relire le message d'erreur.", 2, "Bonne réaction, souvent insuffisante sur une panne inconnue."),
             (IMPULSIVE, "Relancer l'outil plusieurs fois.", 1, "Parfois efficace, mais consomme le temps restant sans diagnostic."),
             (REFORMULATE, "Prévenir le client d'un démarrage différé.", 1, "Préserve la relation ; ne résout pas la panne."),
             (WAIT, "Attendre que cela se rétablisse.", 0, "Inaction devant une échéance de cinq minutes."),
         ]),
    dict(id="TR-107", cat=4, cat_label="Erreur découverte sous pression", targetEmotion="FEAR",
         diff="MODERATE", medium="VIDEO", title="Le chiffre faux dans la présentation",
         context="Pendant votre présentation, vous repérez qu'un chiffre affiché est erroné. Personne ne semble l'avoir vu.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (REFORMULATE, "Signaler l'erreur et donner le bon chiffre.", 3, "Corriger soi-même une erreur non détectée protège la décision et la crédibilité."),
             (WAIT, "Continuer et corriger après la réunion.", 1, "Laisse une décision se prendre sur un chiffre faux."),
             (BREATHE, "Marquer une pause avant de reprendre.", 1, "Évite de se troubler, mais ne corrige rien."),
             (IMPULSIVE, "Vous excuser longuement sur-le-champ.", 1, "Attire l'attention sur l'erreur plus que sur la correction."),
             (ASK, "Demander à l'équipe de vérifier le chiffre.", 2, "Prudent, mais délègue une vérification que vous pouvez faire."),
         ]),
    dict(id="TR-108", cat=4, cat_label="Erreur découverte sous pression", targetEmotion="FEAR",
         diff="HIGH", medium="WRITTEN", title="L'envoi parti au mauvais destinataire",
         context="Vous réalisez qu'un document interne vient de partir à un destinataire externe.",
         message="« Bien reçu, merci. Je regarde ça. » — réponse arrivée trente secondes après votre envoi.",
         question="Que faites-vous maintenant ?",
         choices=[
             (REFORMULATE, "Le prévenir immédiatement de l'erreur et demander la suppression.", 3, "Le destinataire a déjà ouvert : seule une demande explicite et rapide limite la portée."),
             (IMPULSIVE, "Tenter de rappeler le message sans rien dire.", 0, "Le document est déjà lu ; le silence aggrave le risque."),
             (ASK, "Demander conseil à votre responsable avant d'agir.", 2, "Justifié vu l'enjeu, mais chaque minute compte."),
             (BREATHE, "Prendre un instant avant d'agir.", 1, "L'urgence prime ici sur la mise au calme."),
             (WAIT, "Attendre de voir s'il en fait quelque chose.", 0, "Laisse un document interne circuler à l'extérieur."),
         ]),
    dict(id="TR-109", cat=5, cat_label="Désaccord ou tension interpersonnelle", targetEmotion="ANGER",
         diff="MODERATE", medium="VIDEO", title="Le désaccord qui monte",
         context="Un échange sur une méthode de travail se tend : le ton de votre interlocuteur monte, le vôtre aussi.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (BREATHE, "Ralentir et baisser le ton avant de poursuivre.", 3, "La modulation de la réponse est ce qui empêche l'escalade réciproque."),
             (WAIT, "Interrompre l'échange et y revenir plus tard.", 2, "Efficace, mais laisse le désaccord entier."),
             (REFORMULATE, "Reformuler son point avant de donner le vôtre.", 1, "Bon levier, plus difficile quand le ton est déjà monté."),
             (IMPULSIVE, "Maintenir votre position plus fermement.", 0, "Alimente exactement la montée en cours."),
             (ASK, "Lui demander ce qui le gêne précisément.", 1, "Ouvre le dialogue, à condition que le ton le permette."),
         ]),
    dict(id="TR-110", cat=5, cat_label="Désaccord ou tension interpersonnelle", targetEmotion="ANGER",
         diff="HIGH", medium="VIDEO", title="Le reproche répété en tête-à-tête",
         context="Pour la troisième fois ce mois-ci, une collègue vous reproche de ne pas l'avoir consultée.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (ASK, "Lui demander sur quelles décisions elle attend d'être consultée.", 3, "Un reproche répété signale une attente non formulée : la nommer est ce qui arrête la répétition."),
             (REFORMULATE, "Reconnaître le point et proposer un fonctionnement.", 2, "Constructif, mais propose avant d'avoir cerné l'attente."),
             (BREATHE, "Prendre le temps d'accuser réception.", 1, "Utile à la troisième occurrence ; ne suffit pas."),
             (WAIT, "Laisser retomber et en reparler plus tard.", 0, "Un motif récurrent ne se dissout pas avec le temps."),
             (IMPULSIVE, "Rappeler que vous n'avez pas à tout valider.", 1, "Défendable sur le fond, ferme la discussion."),
         ]),
    dict(id="TR-111", cat=6, cat_label="Information incomplète ou ambiguë", targetEmotion="FEAR",
         diff="MODERATE", medium="WRITTEN", title="La consigne à double lecture",
         context="Votre responsable vous transmet une consigne qui peut se comprendre de deux façons opposées.",
         message="« Finalement, ne bloque pas la version de vendredi. »",
         question="Que faites-vous maintenant ?",
         choices=[
             (ASK, "Lui demander laquelle des deux lectures est la bonne.", 3, "Deux lectures opposées : agir sans lever l'ambiguïté revient à parier."),
             (BREATHE, "Relire calmement avant de décider.", 1, "Sain, mais ne lève pas une ambiguïté réelle."),
             (WAIT, "Attendre une précision spontanée.", 1, "Le vendredi approche ; l'attente coûte."),
             (IMPULSIVE, "Choisir la lecture qui vous arrange et avancer.", 0, "Décide à la place du responsable, sur un sujet qu'il a tranché."),
             (REFORMULATE, "Reformuler par écrit ce que vous comprenez, et avancer.", 2, "Bonne pratique ; reste un pari si la réponse n'arrive pas."),
         ]),
    dict(id="TR-112", cat=6, cat_label="Information incomplète ou ambiguë", targetEmotion="FEAR",
         diff="HIGH", medium="VIDEO", title="Le chiffrage sans base",
         context="On vous demande un engagement de délai sur un périmètre que personne n'a encore décrit.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (ASK, "Demander le périmètre avant tout engagement.", 3, "S'engager sur un périmètre inconnu crée une dette qui se paiera au livrable."),
             (WAIT, "Différer la réponse à la description du périmètre.", 1, "Prudent, mais laisse la demande sans réponse."),
             (REFORMULATE, "Donner une fourchette en énonçant les inconnues.", 2, "Utile quand la réponse est attendue tout de suite."),
             (BREATHE, "Prendre un instant avant de répondre.", 1, "Ne remplace pas l'information manquante."),
             (IMPULSIVE, "Donner une date pour ne pas bloquer la réunion.", 0, "Engage l'équipe sur un chiffre sans fondement."),
         ]),
    dict(id="TR-113", cat=7, cat_label="Demande urgente et priorités contradictoires", targetEmotion="FEAR",
         diff="MODERATE", medium="WRITTEN", title="Les deux urgences",
         context="Deux responsables vous demandent la même journée pour deux tâches différentes, chacune présentée comme prioritaire.",
         message="« C'est à faire aujourd'hui, c'est bloquant pour la suite. »",
         question="Que faites-vous maintenant ?",
         choices=[
             (REFORMULATE, "Exposer aux deux le conflit et proposer un ordre.", 3, "Un arbitrage de priorité appartient aux demandeurs : le rendre visible est l'action utile."),
             (ASK, "Demander à chacun ce qui se passe si sa tâche glisse.", 2, "Éclaire l'arbitrage, mais ne le fait pas trancher."),
             (IMPULSIVE, "Commencer par la demande la plus récente.", 0, "Arbitre au hasard, sans que personne ne le sache."),
             (BREATHE, "Faire le point sur votre charge avant de répondre.", 1, "Nécessaire, pas suffisant : le conflit reste invisible pour eux."),
             (WAIT, "Attendre que l'un des deux relance.", 1, "Laisse l'arbitrage se faire par la pression."),
         ]),
    dict(id="TR-114", cat=7, cat_label="Demande urgente et priorités contradictoires", targetEmotion="ANGER",
         diff="HIGH", medium="VIDEO", title="L'ajout en fin de journée",
         context="À 17h, une demande supplémentaire arrive sur un plan de charge déjà complet pour la semaine.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (REFORMULATE, "Accepter en énonçant ce qui sera décalé.", 3, "Accepter sans nommer le coût revient à masquer un retard qui apparaîtra plus tard."),
             (ASK, "Demander le niveau réel d'urgence.", 1, "Utile, mais le plan est déjà saturé quelle que soit la réponse."),
             (WAIT, "Prendre la demande et voir demain.", 1, "Reporte la décision sans réduire la charge."),
             (BREATHE, "Souffler avant de répondre.", 2, "Évite l'acceptation réflexe de fin de journée."),
             (IMPULSIVE, "Refuser sèchement.", 0, "Peut être fondé, mais ferme sans donner d'alternative."),
         ]),
    dict(id="TR-115", cat=8, cat_label="Frustration, refus ou obstacle inattendu", targetEmotion="SADNESS",
         diff="MODERATE", medium="VIDEO", title="Le refus sans explication",
         context="Une demande que vous portiez depuis trois semaines est refusée, sans motif communiqué.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (ASK, "Demander les raisons du refus.", 3, "Sans motif, ni recours ni apprentissage ne sont possibles."),
             (BREATHE, "Encaisser avant de réagir.", 2, "Protège de la réaction à chaud, ne fait pas avancer."),
             (WAIT, "Laisser passer quelques jours.", 1, "Repousse la question sans la traiter."),
             (REFORMULATE, "Redemander en reformulant la demande.", 1, "Prématuré tant que le motif est inconnu."),
             (IMPULSIVE, "Exprimer votre désaccord tout de suite.", 1, "Compréhensible, mais ferme l'accès au motif."),
         ]),
    dict(id="TR-116", cat=8, cat_label="Frustration, refus ou obstacle inattendu", targetEmotion="SADNESS",
         diff="HIGH", medium="VIDEO", title="Le travail refait pour rien",
         context="On vous annonce que le module livré la veille ne sera pas utilisé : la décision a changé.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (BREATHE, "Prendre un temps avant de réagir.", 3, "La frustration est ici légitime et forte : la moduler est le préalable à toute suite utile."),
             (ASK, "Demander ce qui a motivé le changement.", 1, "Utile pour la suite, mais l'affect prime dans l'instant."),
             (REFORMULATE, "Dire calmement ce que le changement a coûté.", 2, "Juste, surtout une fois le premier mouvement passé."),
             (IMPULSIVE, "Exprimer immédiatement votre exaspération.", 0, "Compréhensible, mais adresse le ressenti à qui n'a pas décidé."),
             (WAIT, "Ne rien dire.", 1, "Évite l'éclat ; laisse le coût invisible."),
         ]),
    dict(id="TR-117", cat=9, cat_label="Interruption ou changement de dernière minute", targetEmotion="ANGER",
         diff="MODERATE", medium="VIDEO", title="La coupure répétée",
         context="Vous présentez un point ; le même collègue vous coupe pour la deuxième fois en trois minutes.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (REFORMULATE, "Demander calmement à terminer votre point.", 3, "Reprendre la parole est direct, proportionné, et règle la répétition sur-le-champ."),
             (WAIT, "Le laisser finir et reprendre ensuite.", 2, "Évite l'accroc ; la coupure peut se répéter."),
             (BREATHE, "Marquer un temps avant de continuer.", 1, "Bon réflexe, ne traite pas la cause."),
             (IMPULSIVE, "Élever la voix pour garder la parole.", 0, "Déplace le sujet vers un rapport de force."),
             (ASK, "Lui demander ce qu'il veut ajouter.", 1, "Courtois, mais cède la parole une troisième fois."),
         ]),
    dict(id="TR-118", cat=9, cat_label="Interruption ou changement de dernière minute", targetEmotion="ANGER",
         diff="HIGH", medium="WRITTEN", title="Le report annoncé la veille",
         context="La veille d'une échéance préparée depuis un mois, le cadrage change.",
         message="« Le comité a rebasculé sur l'option B. Peux-tu adapter pour demain matin ? »",
         question="Que faites-vous maintenant ?",
         choices=[
             (ASK, "Demander ce qui doit être présenté demain, au minimum.", 3, "Le périmètre réel du lendemain est la seule information qui rende la nuit utile."),
             (REFORMULATE, "Répondre ce qui est faisable d'ici demain matin.", 2, "Honnête, mais s'engage avant de connaître l'attendu."),
             (BREATHE, "Prendre un moment avant de répondre.", 1, "Évite l'acceptation ou le refus réflexe."),
             (IMPULSIVE, "Accepter tout de suite.", 1, "Engage une nuit de travail sur un attendu non défini."),
             (WAIT, "Attendre demain pour en parler.", 0, "L'échéance est le lendemain matin."),
         ]),
    dict(id="TR-119", cat=10, cat_label="Pression sociale ou hiérarchique", targetEmotion="FEAR",
         diff="MODERATE", medium="VIDEO", title="Le tour de table qui se range",
         context="En réunion, chacun approuve une option que vous jugez risquée. Votre tour arrive.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (WAIT, "Écouter les derniers avis avant de vous prononcer.", 3, "Recueillir l'ensemble avant de se placer est ici la conduite la plus informative — et la moins conformiste."),
             (REFORMULATE, "Exposer calmement le risque que vous voyez.", 2, "Utile, mais avant d'avoir entendu les arguments restants."),
             (ASK, "Demander comment le risque a été traité.", 1, "Ouvre le sujet sans s'opposer frontalement."),
             (IMPULSIVE, "Approuver comme les autres.", 0, "Conformité : le risque reste entier et non dit."),
             (BREATHE, "Prendre un instant avant de parler.", 1, "Sain, insuffisant seul."),
         ]),
    dict(id="TR-120", cat=10, cat_label="Pression sociale ou hiérarchique", targetEmotion="FEAR",
         diff="HIGH", medium="VIDEO", title="La consigne pressante du directeur",
         context="Un directeur vous demande de livrer sans la vérification prévue, en insistant sur le délai.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (WAIT, "Ne pas vous engager dans l'instant.", 2, "Évite l'engagement sous pression, laisse la demande ouverte."),
             (REFORMULATE, "Dire ce que la vérification couvre, et ce qu'on prend comme risque sans elle.", 3, "Rend le risque explicite à celui qui l'assume : c'est ce que la position hiérarchique demande."),
             (IMPULSIVE, "Accepter pour ne pas contrarier.", 0, "Transfère un risque non dit sur le livrable."),
             (ASK, "Demander qui assume l'écart si un défaut passe.", 1, "Pertinent, mais formulé comme une mise en cause."),
             (BREATHE, "Prendre un temps avant de répondre.", 1, "Nécessaire face à la pression, ne résout pas la demande."),
         ]),
    dict(id="TR-121", cat=8, cat_label="Frustration, refus ou obstacle inattendu", targetEmotion="SADNESS",
         diff="MODERATE", medium="VIDEO", title="La reconnaissance qui va à un autre",
         context="En réunion, le travail que vous avez porté est félicité — au nom d'un collègue.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (BREATHE, "Accuser le coup sans réagir tout de suite.", 3, "La déception est vive et l'instant public : moduler la réponse précède toute mise au point utile."),
             (REFORMULATE, "Préciser devant le groupe qui a fait quoi.", 2, "Légitime, mais transforme une reconnaissance en rectificatif devant tous."),
             (ASK, "Demander au collègue s'il a mentionné votre part.", 1, "Question rhétorique : vous venez d'entendre la réponse."),
             (WAIT, "Ne rien dire et passer à la suite.", 1, "Évite l'accroc, laisse l'attribution erronée s'installer."),
             (IMPULSIVE, "Couper pour rétablir immédiatement.", 0, "Déplace un moment de félicitations vers un conflit d'attribution."),
         ]),
    dict(id="TR-122", cat=5, cat_label="Désaccord ou tension interpersonnelle", targetEmotion="SADNESS",
         diff="HIGH", medium="VIDEO", title="Le départ annoncé",
         context="Une collègue avec qui vous travaillez depuis trois ans annonce son départ, et vous l'apprenez en réunion comme tout le monde.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (WAIT, "Laisser passer la réunion avant d'en parler avec elle.", 3, "Une perte relationnelle ne se traite pas en séance : différer protège l'échange qui compte."),
             (BREATHE, "Prendre le temps d'encaisser la nouvelle.", 2, "Utile, mais ne fait rien du lien lui-même."),
             (ASK, "Lui demander devant tous pourquoi elle part.", 0, "Expose un choix personnel devant le groupe."),
             (REFORMULATE, "Dire en séance ce que sa présence a apporté.", 1, "Bienveillant, mais adressé au groupe plus qu'à elle."),
             (IMPULSIVE, "Réagir à chaud sur le manque d'information.", 0, "Confond la nouvelle et la manière dont elle est annoncée."),
         ]),
    dict(id="TR-123", cat=2, cat_label="Critique soudaine ou accusation injuste", targetEmotion="SADNESS",
         diff="MODERATE", medium="WRITTEN", title="Le client qui met fin",
         context="Un client suivi depuis deux ans annonce par écrit qu'il arrête la collaboration.",
         message="« Nous avons décidé de ne pas reconduire. Merci pour ces deux années. »",
         question="Que faites-vous maintenant ?",
         choices=[
             (ASK, "Lui demander ce qui a motivé la décision.", 3, "La décision est actée : l'information est ce qui reste à en tirer, pour la suite."),
             (BREATHE, "Prendre un moment avant de répondre.", 2, "Évite une réponse teintée de déception."),
             (REFORMULATE, "Proposer de revoir les conditions.", 1, "Tente de renégocier une décision annoncée comme prise."),
             (WAIT, "Ne pas répondre dans l'immédiat.", 1, "Laisse le message sans accusé de réception."),
             (IMPULSIVE, "Répondre à chaud sur le peu d'explications.", 0, "Termine deux ans de relation sur un reproche."),
         ]),
    dict(id="TR-124", cat=4, cat_label="Erreur découverte sous pression", targetEmotion="SADNESS",
         diff="HIGH", medium="VIDEO", title="L'échec collectif",
         context="Le projet sur lequel toute l'équipe a travaillé six mois n'a pas atteint son objectif. La réunion de bilan commence.",
         message=None,
         question="Que faites-vous maintenant ?",
         choices=[
             (BREATHE, "Prendre un temps avant de prendre la parole.", 3, "L'affect collectif est au plus haut : se poser d'abord est ce qui rend le bilan exploitable."),
             (ASK, "Demander ce que chacun retient.", 2, "Bon levier de bilan, prématuré tant que l'émotion est vive."),
             (REFORMULATE, "Rappeler ce qui a malgré tout été construit.", 1, "Juste, mais peut sonner comme un déni si c'est le premier mot."),
             (WAIT, "Laisser les autres s'exprimer d'abord.", 2, "Prudent ; risque de laisser le bilan partir sur les reproches."),
             (IMPULSIVE, "Désigner ce qui a coincé, tout de suite.", 0, "Ouvre le bilan sur la recherche d'un responsable."),
         ]),
]
