name: progress_careers
description: Application mobile Zennyt — Flutter, Clean Architecture.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5

  # Injection de dépendances
  get_it: ^7.7.0
  injectable: ^2.4.4

  # Réseau
  dio: ^5.5.0

  # Programmation fonctionnelle (Either<Failure, T>)
  dartz: ^0.10.1

  # Navigation
  go_router: ^14.2.0

  # Cache local (offline-first)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Stockage sécurisé (tokens)
  flutter_secure_storage: ^9.2.2

  # Temps réel & push
  web_socket_channel: ^3.0.0
  firebase_messaging: ^15.0.0

  # Modèles immuables
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Génération de code
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

  # Tests
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
