package com.zennyt.shared.infrastructure.persistence;

import org.hibernate.MappingException;
import org.hibernate.dialect.DatabaseVersion;
import org.hibernate.dialect.PostgreSQLDialect;
import org.hibernate.dialect.identity.IdentityColumnSupport;
import org.hibernate.dialect.identity.PostgreSQLIdentityColumnSupport;
import org.hibernate.engine.jdbc.dialect.spi.DialectResolutionInfo;
import org.hibernate.type.SqlTypes;

import java.sql.Types;

/**
 * Dialecte PostgreSQL du projet : le schéma est généré par Hibernate à partir des
 * entités JPA ({@code ddl-auto: update}), et doit rester identique au schéma
 * historique construit par les migrations Flyway V1..V86.
 *
 * <p>Trois écarts de rendu DDL par rapport à {@link PostgreSQLDialect}, et seulement
 * trois — le SQL d'exécution (requêtes, insertions, récupération des clés) est
 * strictement celui du dialecte standard :
 * <ul>
 *   <li><b>Horodatages en {@code timestamp with time zone}</b>, sans précision
 *       explicite : Hibernate 6 écrit {@code timestamp(6) with time zone}. Même
 *       stockage (la microseconde est la précision par défaut de PostgreSQL), mais
 *       c'est la forme de toutes les colonnes historiques.</li>
 *   <li><b>Clés auto-incrémentées en {@code bigserial}</b> : Hibernate 6 génère
 *       {@code generated by default as identity}, alors que toutes les tables
 *       historiques utilisent {@code bigserial} (séquence {@code <table>_id_seq}
 *       possédée par la colonne). Même comportement à l'insertion, mais deux bases
 *       ne doivent pas diverger selon qu'elles ont été créées avant ou après
 *       l'abandon de Flyway.</li>
 *   <li><b>Aucune contrainte CHECK implicite par colonne</b> : Hibernate 6 ajoute
 *       d'office un {@code CHECK (col IN (...))} sur chaque colonne
 *       {@code @Enumerated}. Le schéma historique a ses propres CHECK, nommés et
 *       parfois plus stricts ; ils sont tous déclarés explicitement sur les
 *       entités ({@code @Check(name = ...)}, contraintes de table, que ce dialecte
 *       continue de générer). Laisser Hibernate en inventer d'autres créerait des
 *       doublons sous d'autres noms.</li>
 * </ul>
 */
public class ZennytPostgreSQLDialect extends PostgreSQLDialect {

    public ZennytPostgreSQLDialect() {
        super();
    }

    public ZennytPostgreSQLDialect(DialectResolutionInfo info) {
        super(info);
    }

    public ZennytPostgreSQLDialect(DatabaseVersion version) {
        super(version);
    }

    @Override
    protected String columnType(int sqlTypeCode) {
        return switch (sqlTypeCode) {
            case SqlTypes.TIMESTAMP_WITH_TIMEZONE, SqlTypes.TIMESTAMP_UTC -> "timestamp with time zone";
            default -> super.columnType(sqlTypeCode);
        };
    }

    @Override
    public IdentityColumnSupport getIdentityColumnSupport() {
        return SerialIdentityColumnSupport.INSTANCE;
    }

    @Override
    public boolean supportsColumnCheck() {
        return false;
    }

    /**
     * Identité rendue en {@code serial}/{@code bigserial} dans le DDL ; tout le reste
     * (sélection de la clé générée, insertions) est hérité du support PostgreSQL standard.
     */
    static final class SerialIdentityColumnSupport extends PostgreSQLIdentityColumnSupport {

        static final SerialIdentityColumnSupport INSTANCE = new SerialIdentityColumnSupport();

        @Override
        public boolean hasDataTypeInIdentityColumn() {
            return false;
        }

        @Override
        public String getIdentityColumnString(int type) {
            return switch (type) {
                case Types.BIGINT -> "bigserial not null";
                case Types.INTEGER -> "serial not null";
                case Types.SMALLINT -> "smallserial not null";
                default -> throw new MappingException(
                    "Type SQL " + type + " non pris en charge pour une clé auto-incrémentée");
            };
        }
    }
}
